# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import sys
from pathlib import Path

current_path = Path().absolute()
print(current_path)
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, str(current_path.parent / "src"))
sys.path.insert(0, str(current_path.parent / "src" / "logs"))
sys.path.insert(0, str(current_path.parent / "config"))
print(sys.path)
project = 'Workshop_Git'
copyright = '2023, ACE'
author = 'ACE'
release = '0.0.1'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ['sphinx.ext.autodoc',
'sphinx.ext.doctest',
'recommonmark',
'sphinx.ext.autosectionlabel',
]

templates_path = ['.templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
source_suffix = ['.rst', '.md']
master_doc = 'index'

pygments_style = 'sphinx'
todo_icnlude_todos = True
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

project = u'GitHub Workshop'
author = u'Alexandre Condette'
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

latex_elements={}

latex_documents= [
(master_doc, project, u'Documentation',
author, 'manual'),]

man_pages = [
(master_doc, project, u'Documentation',
[author], 1),]

textinfo_documents = [
(master_doc, project, u'Documentation',
author, project, 'manual', 'misc'),]

source_parsers = {
'.md': 'recommonmark.parser.CommonMarkParser'}
